### ISSUE TITLE
Acceso para no staff

### ISSUE THREAD

**Issue by leliel12** [ivco19/brooks#8]
Reimplemente el parseo de datos sin usar atomic que dabe mil problemas, simplifique un monton el codigo (aun no implemente el merge, pero es un poco mas de codigo y esta).

Te pido uno de los ultimos dos requerimientos: Si el usuario no staff, lo deberia mandar dercho a "subir un archivo" pero no puede "mergear". Ademas en la lista de archivos cargados deberia ver solo los suyos.

Tampoco puede navegar por los modelos cargados. En resumen solo puede

- Subir un archivo.
- Ver que archivos subio el, y en que estado estan.
- Tambien puede cambiar sus notas en el archivo obviamente.

**Comment by leliel12** [comment]
@mgaitan podes fijarte esto?

**Comment by mgaitan** [comment]
Ok, mañana lo hago

**Comment by mgaitan** [comment]
:+1:
